apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cc.fullname" . }}
  labels:
{{ include "cc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "cc.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "cc.labels" . | indent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      topologySpreadConstraints:
        # Hard rule: don't place multiple replicas on the same node
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
{{ include "cc.labels" . | indent 14 }}

        # Soft rule: try to spread across AZs too (won't block scheduling)
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
{{ include "cc.labels" . | indent 14 }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}

      containers:
        - name: control-center
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: TEMPORAL_TARGET
              value: {{ quote .Values.env.TEMPORAL_TARGET }}

          {{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{- end }}


      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}

